apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bonus-application
spec:
  project: default
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    targetRevision: HEAD
    repoURL: http://bonus-gitlab-service.gitlab.svc.cluster.local/root/iot-p3-deployment.git
    path: manifest
  syncPolicy:
    automated:
      selfHeal: true

