Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.build_dir = "confs"
    d.create_args = ["--cgroupns=host", "-v", "/sys/fs/cgroup:/sys/fs/cgroup:rw"]
    d.remains_running = true
    d.has_ssh = true
    d.privileged = true
  end
  config.ssh.insert_key = true 
  config.vm.define "rgillesS" do |control|
    control.vm.hostname = "rgillesS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provision "shell", privileged: true, path: "scripts/server.sh"
  end 
  config.vm.define "rgillesSW" do |control|
    control.vm.hostname = "rgillesSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provision "shell", privileged: true, path: "scripts/worker.sh"
  end
end

