apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-p3-argocd
  namespace: argocd
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: argocd-server
            port:
              number: 80
